update v26

diff --git a/buildspec.sonar.yml b/buildspec.sonar.yml
--- a/buildspec.sonar.yml
+++ b/buildspec.sonar.yml
@@ -46,10 +46,10 @@ phases:
       - curl $Host/api/qualitygates/project_status?projectKey=$Project > result.json
       - cat result.json
       - if [ "$(jq -r '.projectStatus.status' result.json)" = "ERROR" ]; then
-          echo "Quality gate failed. SonarQube reported an ERROR status."
-          exit 1
+          echo "Quality gate failed. SonarQube reported an ERROR status.";
+          exit 1;
         else
-          echo "Quality gate passed. SonarQube reported a SUCCESS status."
+          echo "Quality gate passed. SonarQube reported a SUCCESS status.";
         fi
 cache:
   paths:
